name: mock

on:
  workflow_call:
    outputs:
      job-three-success:
        description: "Whether job-three succeeded"
        value: ${{ jobs.job-three.outputs.status }}
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: This job always succeeds
        run: echo "Job one succeeded ✅"

  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    continue-on-error: true
    steps:
      - name: This job always fails
        run: |
          echo "Job two failed ❌"
          exit 1

  job-three:
    runs-on: ubuntu-latest
    needs: job-two
    if: always() # Run even if job-two fails
    continue-on-error: true
    outputs:
      status: ${{ steps.output-step.outcome }}
    steps:
      - id: output-step
        run: |
          echo "result==success" >> $GITHUB_ENV