name: mock

on:
  workflow_call:
    outputs:
      job-three-success:
        description: "Whether job-three succeeded"
        value: ${{ steps.output-step.outputs.message == 'true' }}
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: This job always succeeds
        run: echo "Job one succeeded ✅"

  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - name: This job always fails
        run: |
          echo "Job two failed ❌"
          exit 1

  job-three:
    runs-on: ubuntu-latest
    needs: job-two
    if: always() # Run even if job-two fails
    outputs:
      result: ${{ steps.output-step.outputs.message }}
    steps:
      - id: output-step
        run: |
          # Set the message to true if you want to indicate success
          echo "message=true"