name: Send Slack message
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      SLACK_CHANNEL_TESTER:
        required: true
      SLACK_TOKEN:
        required: true

jobs:
  slack:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: post slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          slack-message: |
              "new issue: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }} created."
          channel-id: ${{ secrets.SLACK_CHANNEL_TESTER }}