name: Model test on PR

on:
  workflow_call:

jobs:
  model-test:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - uses: actions/checkout@v4.2.2
        with:
          lfs: true
          
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          auto-activate-base: false

      - name: Install dependencies
        run: |
          conda run -n base git-lfs install
          conda run -n base conda install gh -c conda-forge
          conda run -n base python -m pip install 'git+https://github.com/ersilia-os/ersilia.git#egg=ersilia[test]'

      - name: Fetch model and run #TODO change for test command 
        env:
          MODEL_ID: ${{ github.event.repository.name }}
        run: |
          conda run -n base bash -c "
            ersilia -v fetch $MODEL_ID --from_github &&
            ersilia serve $MODEL_ID &&
            ersilia example -f input.csv -n 3 &&
            ersilia run -i input.csv -o output.csv &&
            ersilia close &&
            ersilia delete $MODEL_ID &&
            head output.csv
          "
          
      - name: Upload log output
        if: always()
        uses: actions/upload-artifact@v4.5.0
        with:
          name: debug-logs
          retention-days: 14
          path: |
            /home/runner/eos/*.log
            ./*.log
