name: Test model image debug

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  test-image-arm64:
    runs-on: default-linux-arm64
    steps:
      - name: print architecture
        run: |
          echo "Architecture: $(uname -m)"
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          auto-activate-base: false

      - name: Debug Conda environments
        run: |
          conda info
          conda env list

      - name: Install dependencies
        run: |
          conda run -n base python -m pip install 'git+https://github.com/ersilia-os/ersilia.git#egg=ersilia[test]'
          conda run -n base ersilia --version

      - name: Test ARM64 image
        env:
          MODEL_ID: ${{ inputs.repo_name }}
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate base
          ersilia -v test $MODEL_ID --deep --from_dockerhub --version dev-arm64

      - name: Parse test results
        env:
          MODEL_ID: ${{ inputs.repo_name }}
        run: |
          TEST_JSON="${MODEL_ID}-test.json"
          
          if [[ ! -f "$TEST_JSON" ]]; then
            echo "Error: Test results file $TEST_JSON not found!"
            exit 1
          fi
          mv "${MODEL_ID}-test.json" "${MODEL_ID}-test-arm64.json"
          TEST_JSON="${MODEL_ID}-test-arm64.json"
          echo "Parsing test results from $TEST_JSON"

          TEST_FAILED=$(jq 'recurse | objects | select(map(select(. == false)) | length > 0)' "$TEST_JSON")
              if [[ -n "$TEST_FAILED" ]]; then
                echo "❌ Some tests failed. Stopping workflow."
                exit 1
              fi
